// codeshaunted - gooforge
// include/gooforge/level.hh
// contains Level declarations
// Copyright 2024 codeshaunted
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org / licenses / LICENSE - 2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissionsand
// limitations under the License.

#ifndef GOOFORGE_LEVEL_HH
#define GOOFORGE_LEVEL_HH

#include <expected>

#include "simdjson.h"

#include "error.hh"
#include "goo_ball.hh"
#include "goo_strand.hh"
#include "vector.hh"

namespace gooforge {

struct TerrainGroupInfo {
	Vector2f textureOffset;
	std::string typeUuid;
	int typeIndex;
	int sortOffset;
	float depth;
	bool foreground;
	bool collision;
	bool destructable;
	bool buildable;
	bool occluder;
};

// if you think this name is too long,
// so do i, but this is literally the
// name directly from the binary
struct ItemInstanceUserVariableInfo {
	float value;
};

struct ItemInstanceInfo {
	std::string id;
	std::string type;
	std::string localizedStringId;
	unsigned int uid;
	Vector2f pos;
	Vector2f scale;
	float rotation;
	float depth;
	bool flipHorizontal;
	bool flipVertical;
	float rotSpeed;
	int seed;
	int liquidType; 
	unsigned int adapterBallId;
	bool invisible;
	int forcedRandomizationIndex;
	std::string particleEffectName;
	int uid1;
	int uid2;
	std::vector<ItemInstanceUserVariableInfo> userVariables;
};

struct PinInfo {
	unsigned int uid;
	Vector2f pos;
	float damping;
	bool limitVelocity;
	float maxVelocity;
};

struct InitialCameraKeyframeInfo {
	Vector2f position;
	float zoom;
	float timeScaleFactor;
	float timeScaleFactor2;
	float pauseTimeFactor;
	float easeInSpeedFactor;
	float easeOutSpeedFactor;
};

struct TerrainBallInfo {
	int group;
};

struct LevelInfo {
	std::string _gooforge = "This file was generated by gooforge v0.1";
	int version;
	int type;
	bool forceFadeEOL;
	int skin;
	std::string uuid;
	std::string title;
	int startingUID;
	int island;
	int environmentId;
	std::string backgroundId;
	Vector2f gravity;
	Vector2f boundsTopRight;
	Vector2f boundsBottomLeft;
	Vector2f initialCameraPos;
	float initialCameraZoom;
	bool cameraAutoBounds;
	float ballsRateRequired;
	std::string musicId;
	std::string ambienceId;
	float liquidScale;
	float pretickSeconds;
	float conduitSuckVolume;
	float fireSfxVolume;
	std::vector<GooBallInfo> balls;
	std::vector<GooStrandInfo> strands;
	std::vector<TerrainGroupInfo> terrainGroups;
	std::vector<ItemInstanceInfo> items;
	std::vector<PinInfo> pins;
	std::vector<InitialCameraKeyframeInfo> initialCameraKeyframes;
	std::vector<TerrainBallInfo> terrainBalls;
	std::vector<std::string> levelEnvironmentEffects;
	bool enableTimeBugs;
	int timebugMoves;
};

class Level {
	public:
		Level(LevelInfo info);
		~Level();
		void addEntity(Entity* entity);
		void update();
		void draw(sf::RenderWindow* window);
		static sf::Vector2f worldToScreen(Vector2f world);
		static Vector2f screenToWorld(sf::Vector2f screen);
	private:
		void sortEntities();
		LevelInfo info;
		std::vector<Entity*> entities;
		bool entities_dirty = false;

	friend class Editor;
};

} // namespace gooforge

#endif // GOOFORGE_LEVEL_HH